name: strainprox
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - numpy=1.19.2
  - scipy=1.5.2
  - matplotlib=3.5.3
  - jupyter=1.0.0
  - pandas=1.4.4
  - pip:
    - pylops==2.1.0
    - pyproximal==0.9.0


