name: strainprox2
channels:
  - pytorch
  - conda-forge
  - defaults
  - rapidsai
  - nvidia
dependencies:
  - python=3.11
  - pip
  - numpy
  - segyio
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets
  - cupy
  - cusignal
  - pylops
  - pyproximal
  - pytorch==2.5.1
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - torchinfo
  
